export interface District {
  id: number;
  value: string;
  label: string;
}

interface CityDistricts {
  [key: string]: District[];
}

export const DistrictOptions: CityDistricts = {
  seoul: [
    {id: 1, value: 'gangnam', label: '강남구'},
    {id: 2, value: 'gangdong', label: '강동구'},
    {id: 3, value: 'gangbuk', label: '강북구'},
    {id: 4, value: 'gangseo', label: '강서구'},
    {id: 5, value: 'gwanak', label: '관악구'},
    {id: 6, value: 'gwangjin', label: '광진구'},
    {id: 7, value: 'guro', label: '구로구'},
    {id: 8, value: 'geumcheon', label: '금천구'},
    {id: 9, value: 'nowon', label: '노원구'},
    {id: 10, value: 'dobong', label: '도봉구'},
    {id: 11, value: 'dongdaemun', label: '동대문구'},
    {id: 12, value: 'dongjak', label: '동작구'},
    {id: 13, value: 'mapo', label: '마포구'},
    {id: 14, value: 'seodaemun', label: '서대문구'},
    {id: 15, value: 'seocho', label: '서초구'},
    {id: 16, value: 'seongdong', label: '성동구'},
    {id: 17, value: 'seongbuk', label: '성북구'},
    {id: 18, value: 'songpa', label: '송파구'},
    {id: 19, value: 'yangcheon', label: '양천구'},
    {id: 20, value: 'yeongdeungpo', label: '영등포구'},
    {id: 21, value: 'yongsan', label: '용산구'},
    {id: 22, value: 'eunpyeong', label: '은평구'},
    {id: 23, value: 'jongno', label: '종로구'},
    {id: 24, value: 'jung', label: '중구'},
    {id: 25, value: 'jungnang', label: '중랑구'},
  ],
  busan: [
    {id: 1, value: 'gangseo', label: '강서구'},
    {id: 2, value: 'geumjeong', label: '금정구'},
    {id: 3, value: 'gijang', label: '기장군'},
    {id: 4, value: 'nam', label: '남구'},
    {id: 5, value: 'dong', label: '동구'},
    {id: 6, value: 'dongnae', label: '동래구'},
    {id: 7, value: 'busanjin', label: '부산진구'},
    {id: 8, value: 'buk', label: '북구'},
    {id: 9, value: 'sasang', label: '사상구'},
    {id: 10, value: 'saha', label: '사하구'},
    {id: 11, value: 'seo', label: '서구'},
    {id: 12, value: 'suyeong', label: '수영구'},
    {id: 13, value: 'yeonje', label: '연제구'},
    {id: 14, value: 'yeongdo', label: '영도구'},
    {id: 15, value: 'jung', label: '중구'},
    {id: 16, value: 'haeundae', label: '해운대구'},
  ],
  daegu: [
    {id: 1, value: 'nam', label: '남구'},
    {id: 2, value: 'dalseo', label: '달서구'},
    {id: 3, value: 'dalseong', label: '달성군'},
    {id: 4, value: 'dong', label: '동구'},
    {id: 5, value: 'buk', label: '북구'},
    {id: 6, value: 'seo', label: '서구'},
    {id: 7, value: 'suseong', label: '수성구'},
    {id: 8, value: 'jung', label: '중구'},
  ],
  incheon: [
    {id: 1, value: 'gyeyang', label: '계양구'},
    {id: 2, value: 'michuhol', label: '미추홀구'},
    {id: 3, value: 'namdong', label: '남동구'},
    {id: 4, value: 'dong', label: '동구'},
    {id: 5, value: 'bupyeong', label: '부평구'},
    {id: 6, value: 'seo', label: '서구'},
    {id: 7, value: 'yeonsu', label: '연수구'},
    {id: 8, value: 'jung', label: '중구'},
    {id: 9, value: 'ganghwa', label: '강화군'},
    {id: 10, value: 'ongjin', label: '옹진군'},
  ],
  gwangju: [
    {id: 1, value: 'gwangsan', label: '광산구'},
    {id: 2, value: 'nam', label: '남구'},
    {id: 3, value: 'dong', label: '동구'},
    {id: 4, value: 'buk', label: '북구'},
    {id: 5, value: 'seo', label: '서구'},
  ],
  daejeon: [
    {id: 1, value: 'daedeok', label: '대덕구'},
    {id: 2, value: 'dong', label: '동구'},
    {id: 3, value: 'seo', label: '서구'},
    {id: 4, value: 'yuseong', label: '유성구'},
    {id: 5, value: 'jung', label: '중구'},
  ],
  ulsan: [
    {id: 1, value: 'nam', label: '남구'},
    {id: 2, value: 'dong', label: '동구'},
    {id: 3, value: 'buk', label: '북구'},
    {id: 4, value: 'ulju', label: '울주군'},
    {id: 5, value: 'jung', label: '중구'},
  ],
  sejong: [{id: 1, value: 'sejong', label: '세종시'}],
  gyeonggi: [
    {id: 1, value: 'gapyeong', label: '가평군'},
    {id: 2, value: 'goyang_deogyang', label: '고양시 덕양구'},
    {id: 3, value: 'goyang_ilsandong', label: '고양시 일산동구'},
    {id: 4, value: 'goyang_ilsanseo', label: '고양시 일산서구'},
    {id: 5, value: 'gwacheon', label: '과천시'},
    {id: 6, value: 'gwangmyeong', label: '광명시'},
    {id: 7, value: 'gwangju', label: '광주시'},
    {id: 8, value: 'guri', label: '구리시'},
    {id: 9, value: 'gunpo', label: '군포시'},
    {id: 10, value: 'gimpo', label: '김포시'},
    {id: 11, value: 'namyangju', label: '남양주시'},
    {id: 12, value: 'dongducheon', label: '동두천시'},
    {id: 13, value: 'bucheon', label: '부천시'},
    {id: 14, value: 'seongnam_bundang', label: '성남시 분당구'},
    {id: 15, value: 'seongnam_sujeong', label: '성남시 수정구'},
    {id: 16, value: 'seongnam_jungwon', label: '성남시 중원구'},
    {id: 17, value: 'suwon_kwonseon', label: '수원시 권선구'},
    {id: 18, value: 'suwon_yeongtong', label: '수원시 영통구'},
    {id: 19, value: 'suwon_jangan', label: '수원시 장안구'},
    {id: 20, value: 'suwon_paldal', label: '수원시 팔달구'},
    {id: 21, value: 'siheung', label: '시흥시'},
    {id: 22, value: 'ansan_danwon', label: '안산시 단원구'},
    {id: 23, value: 'ansan_sangnok', label: '안산시 상록구'},
    {id: 24, value: 'anseong', label: '안성시'},
    {id: 25, value: 'anyang_dongan', label: '안양시 동안구'},
    {id: 26, value: 'anyang_manan', label: '안양시 만안구'},
    {id: 27, value: 'yangju', label: '양주시'},
    {id: 28, value: 'yangpyeong', label: '양평군'},
    {id: 29, value: 'yeoju', label: '여주시'},
    {id: 30, value: 'yeoncheon', label: '연천군'},
    {id: 31, value: 'osan', label: '오산시'},
    {id: 32, value: 'yongin_giheung', label: '용인시 기흥구'},
    {id: 33, value: 'yongin_suji', label: '용인시 수지구'},
    {id: 34, value: 'yongin_cheoin', label: '용인시 처인구'},
    {id: 35, value: 'uiwang', label: '의왕시'},
    {id: 36, value: 'uijeongbu', label: '의정부시'},
    {id: 37, value: 'icheon', label: '이천시'},
    {id: 38, value: 'paju', label: '파주시'},
    {id: 39, value: 'pyeongtaek', label: '평택시'},
    {id: 40, value: 'pocheon', label: '포천시'},
    {id: 41, value: 'hanam', label: '하남시'},
    {id: 42, value: 'hwaseong', label: '화성시'},
  ],
  gangwon: [
    {id: 1, value: 'gangneung', label: '강릉시'},
    {id: 2, value: 'goseong', label: '고성군'},
    {id: 3, value: 'donghae', label: '동해시'},
    {id: 4, value: 'samcheok', label: '삼척시'},
    {id: 5, value: 'sokcho', label: '속초시'},
    {id: 6, value: 'yanggu', label: '양구군'},
    {id: 7, value: 'yangyang', label: '양양군'},
    {id: 8, value: 'yeongwol', label: '영월군'},
    {id: 9, value: 'wonju', label: '원주시'},
    {id: 10, value: 'inje', label: '인제군'},
    {id: 11, value: 'jeongseon', label: '정선군'},
    {id: 12, value: 'cheorwon', label: '철원군'},
    {id: 13, value: 'chuncheon', label: '춘천시'},
    {id: 14, value: 'taebaek', label: '태백시'},
    {id: 15, value: 'pyeongchang', label: '평창군'},
    {id: 16, value: 'hongcheon', label: '홍천군'},
    {id: 17, value: 'hwacheon', label: '화천군'},
    {id: 18, value: 'hoengseong', label: '횡성군'},
  ],
  chungbuk: [
    {id: 1, value: 'goesan', label: '괴산군'},
    {id: 2, value: 'danyang', label: '단양군'},
    {id: 3, value: 'boeun', label: '보은군'},
    {id: 4, value: 'yeongdong', label: '영동군'},
    {id: 5, value: 'okcheon', label: '옥천군'},
    {id: 6, value: 'eumseong', label: '음성군'},
    {id: 7, value: 'jecheon', label: '제천시'},
    {id: 8, value: 'jeungpyeong', label: '증평군'},
    {id: 9, value: 'jincheon', label: '진천군'},
    {id: 10, value: 'cheongju_sangdang', label: '청주시 상당구'},
    {id: 11, value: 'cheongju_seowon', label: '청주시 서원구'},
    {id: 12, value: 'cheongju_cheongwon', label: '청주시 청원구'},
    {id: 13, value: 'cheongju_heungdeok', label: '청주시 흥덕구'},
    {id: 14, value: 'chungju', label: '충주시'},
  ],
  chungnam: [
    {id: 1, value: 'gyeryong', label: '계룡시'},
    {id: 2, value: 'gongju', label: '공주시'},
    {id: 3, value: 'geumsan', label: '금산군'},
    {id: 4, value: 'nonsan', label: '논산시'},
    {id: 5, value: 'dangjin', label: '당진시'},
    {id: 6, value: 'boryeong', label: '보령시'},
    {id: 7, value: 'buyeo', label: '부여군'},
    {id: 8, value: 'seosan', label: '서산시'},
    {id: 9, value: 'seocheon', label: '서천군'},
    {id: 10, value: 'asan', label: '아산시'},
    {id: 11, value: 'yeongi', label: '연기군'},
    {id: 12, value: 'yesan', label: '예산군'},
    {id: 13, value: 'cheonan_dongnam', label: '천안시 동남구'},
    {id: 14, value: 'cheonan_seobuk', label: '천안시 서북구'},
    {id: 15, value: 'cheongyang', label: '청양군'},
    {id: 16, value: 'taean', label: '태안군'},
    {id: 17, value: 'hongseong', label: '홍성군'},
  ],
  jeonbuk: [
    {id: 1, value: 'gochang', label: '고창군'},
    {id: 2, value: 'gunsan', label: '군산시'},
    {id: 3, value: 'gimje', label: '김제시'},
    {id: 4, value: 'namwon', label: '남원시'},
    {id: 5, value: 'muju', label: '무주군'},
    {id: 6, value: 'buan', label: '부안군'},
    {id: 7, value: 'sunchang', label: '순창군'},
    {id: 8, value: 'wanju', label: '완주군'},
    {id: 9, value: 'iksan', label: '익산시'},
    {id: 10, value: 'imsil', label: '임실군'},
    {id: 11, value: 'jangsu', label: '장수군'},
    {id: 12, value: 'jeonju_deokjin', label: '전주시 덕진구'},
    {id: 13, value: 'jeonju_wansan', label: '전주시 완산구'},
    {id: 14, value: 'jeongeup', label: '정읍시'},
    {id: 15, value: 'jinan', label: '진안군'},
  ],
  jeonnam: [
    {id: 1, value: 'gangjin', label: '강진군'},
    {id: 2, value: 'goheung', label: '고흥군'},
    {id: 3, value: 'gokseong', label: '곡성군'},
    {id: 4, value: 'gwangyang', label: '광양시'},
    {id: 5, value: 'gurye', label: '구례군'},
    {id: 6, value: 'naju', label: '나주시'},
    {id: 7, value: 'damyang', label: '담양군'},
    {id: 8, value: 'mokpo', label: '목포시'},
    {id: 9, value: 'muan', label: '무안군'},
    {id: 10, value: 'boseong', label: '보성군'},
    {id: 11, value: 'suncheon', label: '순천시'},
    {id: 12, value: 'sinan', label: '신안군'},
    {id: 13, value: 'yeosu', label: '여수시'},
    {id: 14, value: 'yeonggwang', label: '영광군'},
    {id: 15, value: 'yeongam', label: '영암군'},
    {id: 16, value: 'wando', label: '완도군'},
    {id: 17, value: 'jangseong', label: '장성군'},
    {id: 18, value: 'jangheung', label: '장흥군'},
    {id: 19, value: 'jindo', label: '진도군'},
    {id: 20, value: 'hampyeong', label: '함평군'},
    {id: 21, value: 'haenam', label: '해남군'},
    {id: 22, value: 'hwaseong', label: '화순군'},
  ],
  gyeongbuk: [
    {id: 1, value: 'gyeongsan', label: '경산시'},
    {id: 2, value: 'gyeongju', label: '경주시'},
    {id: 3, value: 'goryeong', label: '고령군'},
    {id: 4, value: 'gumi', label: '구미시'},
    {id: 5, value: 'gunwi', label: '군위군'},
    {id: 6, value: 'gimcheon', label: '김천시'},
    {id: 7, value: 'mungyeong', label: '문경시'},
    {id: 8, value: 'bonghwa', label: '봉화군'},
    {id: 9, value: 'sangju', label: '상주시'},
    {id: 10, value: 'seongju', label: '성주군'},
    {id: 11, value: 'andong', label: '안동시'},
    {id: 12, value: 'yeongdeok', label: '영덕군'},
    {id: 13, value: 'yeongyang', label: '영양군'},
    {id: 14, value: 'yeongju', label: '영주시'},
    {id: 15, value: 'yeongcheon', label: '영천시'},
    {id: 16, value: 'yecheon', label: '예천군'},
    {id: 17, value: 'ulleung', label: '울릉군'},
    {id: 18, value: 'uljin', label: '울진군'},
    {id: 19, value: 'uiseong', label: '의성군'},
    {id: 20, value: 'cheongdo', label: '청도군'},
    {id: 21, value: 'cheongsong', label: '청송군'},
    {id: 22, value: 'chilgok', label: '칠곡군'},
    {id: 23, value: 'pohang_nam', label: '포항시 남구'},
    {id: 24, value: 'pohang_buk', label: '포항시 북구'},
  ],
  gyeongnam: [
    {id: 1, value: 'geoje', label: '거제시'},
    {id: 2, value: 'geochang', label: '거창군'},
    {id: 3, value: 'goseong', label: '고성군'},
    {id: 4, value: 'gimhae', label: '김해시'},
    {id: 5, value: 'namhae', label: '남해군'},
    {id: 6, value: 'miryang', label: '밀양시'},
    {id: 7, value: 'sacheon', label: '사천시'},
    {id: 8, value: 'sancheong', label: '산청군'},
    {id: 9, value: 'yangsan', label: '양산시'},
    {id: 10, value: 'uiryeong', label: '의령군'},
    {id: 11, value: 'jinju', label: '진주시'},
    {id: 12, value: 'changnyeong', label: '창녕군'},
    {id: 13, value: 'changwon_masan_happo', label: '창원시 마산합포구'},
    {id: 14, value: 'changwon_masan_hoewon', label: '창원시 마산회원구'},
    {id: 15, value: 'changwon_seongsan', label: '창원시 성산구'},
    {id: 16, value: 'changwon_uitdong', label: '창원시 의창구'},
    {id: 17, value: 'changwon_jinhae', label: '창원시 진해구'},
    {id: 18, value: 'tongyeong', label: '통영시'},
    {id: 19, value: 'hadong', label: '하동군'},
    {id: 20, value: 'haman', label: '함안군'},
    {id: 21, value: 'hamyang', label: '함양군'},
    {id: 22, value: 'hapcheon', label: '합천군'},
  ],
  jeju: [
    {id: 1, value: 'seogwipo', label: '서귀포시'},
    {id: 2, value: 'jeju', label: '제주시'},
  ],
};
